### ISSUE TITLE
Null values in json

### ISSUE THREAD

**Issue by praps35** [siddhi-io/siddhi-execution-json#38]
Is it possible to add null values in json using  `json:Element()` function?

Class :  SetElementJSONFunctionExtensio.java line no: 236 

            if (key != null) {
                Object parsedJsonElement = gson.fromJson(jsonElement.toString(), Object.class);
                if (jsonElement instanceof String && (parsedJsonElement instanceof Map
                        || parsedJsonElement instanceof List)) {
                    documentContext.put(path, key, gson.fromJson(jsonElement.toString(), Object.class));
                } else {
                    documentContext.put(path, key, jsonElement);
                }
                
I am getting null pointer exception here Object parsedJsonElement = gson.fromJson(jsonElement.toString(), Object.class);
in my case, value for  `jsonElement` itself is null.

Is addition of null values is avoided purposely?

**Comment by dcssi** [comment]
Well by looking at the code, the value you are passing is always being parsed, so you can't pass null.  However you can pass something that will parse to null like a json string "{null}"

**Comment by praps35** [comment]
>the value you are passing is always being parsed, so you can't pass null.

Thank you for replying. But in my case, I'm not passing null value directly, whereas I pass some json function which returns null(in case of that attribute's absence) that is being parsed here. 

e.g:
 function — `json:setElement(json, '$.student.roomName',  json:getString(json, '$.roomName')))`
Assume here value for `$.roomName` is null or not present

**Comment by dcssi** [comment]
OK I see.   When you are calling json:getString(json, '$.roomName'), it looks like the row you are processing has no room name so 
json:getString(json, '$.roomName')  returns null.   You need to wrap the call to json:getString(json, '$.roomName') with another function which test for null and replace the value before calling json:setElement.  Siddhi has a function for this (Its been a while since I used siddhi, so I can't remember the function name.  Sorry).  If you can't find it, ping me and I'll look for it.

**Comment by praps35** [comment]
Will check into it, and Thanks for your suggestion :)

**Comment by dcssi** [comment]
Did my suggestion worked ?
